import pytest

from loop.runtime_materializers.codex_agent_toml import markdown_agent_to_codex_toml


def test_markdown_frontmatter_converts_to_toml() -> None:
    src = """---
name: verify-implement
description: "Gate agent"
---
Do verify only.
"""
    out = markdown_agent_to_codex_toml(
        src,
        fallback_name="fallback",
        fallback_description="fallback desc",
    )
    assert out.startswith("# GENERATED by runtime-sync")
    assert 'name = "verify-implement"' in out
    assert 'description = "Gate agent"' in out
    assert "Do verify only." in out
    assert "---" not in out.splitlines()[0]


def test_plain_markdown_uses_fallbacks() -> None:
    out = markdown_agent_to_codex_toml(
        "plain body",
        fallback_name="worker",
        fallback_description="Worker agent",
    )
    assert 'name = "worker"' in out
    assert 'description = "Worker agent"' in out
    assert "plain body" in out
