from __future__ import annotations

from pathlib import Path
import pytest

from loop.runtime_materializers.agents import materialize_agents, MaterializationError
from loop.runtime_materializers.manifest_schema import load_manifest


@pytest.fixture
def sample_agent_manifest(tmp_path: Path) -> Path:
    agents_dir = tmp_path / "harness" / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)
    (agents_dir / "verify-implement.md").write_text("# verify implement prompt", encoding="utf-8")
    (agents_dir / "explorer.md").write_text("# explorer prompt", encoding="utf-8")

    manifest_content = """
schema_version: "harness-manifest/v1"
agents:
  verify-implement:
    description: "Pre-FINISH verify gate for IMPLEMENT"
    source: "harness/agents/verify-implement.md"
    runtimes:
      claude:
        type: "native"
      codex:
        type: "materialize"
        target: ".codex/agents/verify-implement.md"
  explorer:
    description: "Explorer agent"
    source: "harness/agents/explorer.md"
    runtimes:
      claude:
        type: "native"
      codex:
        materialize: true
        target: ".codex/agents/explorer.md"
hooks: {}
instructions: {}
"""
    p = tmp_path / "manifest.yaml"
    p.write_text(manifest_content.strip(), encoding="utf-8")
    return p


def test_materialize_codex_agent_toml_from_frontmatter(sample_agent_manifest: Path, tmp_path: Path) -> None:
    agents_dir = tmp_path / "harness" / "agents"
    (agents_dir / "verify-implement.md").write_text(
        "---\n"
        "name: verify-implement\n"
        'description: "Gate agent"\n'
        "---\n\n"
        "Do verify only.\n",
        encoding="utf-8",
    )
    manifest = load_manifest(sample_agent_manifest)
    manifest_path = sample_agent_manifest
    manifest_content = manifest_path.read_text(encoding="utf-8").replace(
        'target: ".codex/agents/verify-implement.md"',
        'target: ".codex/agents/verify-implement.toml"',
    ).replace(
        'target: ".codex/agents/explorer.md"',
        'target: ".codex/agents/explorer.toml"',
    )
    manifest_path.write_text(manifest_content, encoding="utf-8")
    manifest = load_manifest(manifest_path)

    dest_paths = materialize_agents(manifest, "codex", dest_root=tmp_path, repo_root=tmp_path)

    target_file = tmp_path / ".codex" / "agents" / "verify-implement.toml"
    assert target_file.exists()
    content = target_file.read_text(encoding="utf-8")
    assert content.startswith("# GENERATED by runtime-sync")
    assert 'name = "verify-implement"' in content
    assert 'description = "Gate agent"' in content
    assert "Do verify only." in content
    assert "---" not in content.splitlines()[0]
    assert str(target_file) in dest_paths


def test_materialize_returns_dest_paths(sample_agent_manifest: Path, tmp_path: Path) -> None:
    manifest_content = sample_agent_manifest.read_text(encoding="utf-8").replace(
        ".codex/agents/verify-implement.md",
        ".codex/agents/verify-implement.toml",
    ).replace(
        ".codex/agents/explorer.md",
        ".codex/agents/explorer.toml",
    )
    sample_agent_manifest.write_text(manifest_content, encoding="utf-8")
    manifest = load_manifest(sample_agent_manifest)
    dest_paths = materialize_agents(manifest, "codex", dest_root=tmp_path, repo_root=tmp_path)

    expected = [
        str(tmp_path / ".codex" / "agents" / "verify-implement.toml"),
        str(tmp_path / ".codex" / "agents" / "explorer.toml"),
    ]
    assert sorted(dest_paths) == sorted(expected)


def test_missing_source_raises_materialization_error(tmp_path: Path) -> None:
    manifest_content = """
schema_version: "harness-manifest/v1"
agents:
  missing-agent:
    description: "Missing agent source"
    source: "harness/agents/nonexistent.md"
    runtimes:
      codex:
        type: "materialize"
        target: ".codex/agents/nonexistent.md"
hooks: {}
instructions: {}
"""
    m_file = tmp_path / "manifest.yaml"
    m_file.write_text(manifest_content.strip(), encoding="utf-8")
    manifest = load_manifest(m_file)

    with pytest.raises(MaterializationError):
        materialize_agents(manifest, "codex", dest_root=tmp_path)


def test_native_skipped_for_native_type(sample_agent_manifest: Path, tmp_path: Path) -> None:
    manifest = load_manifest(sample_agent_manifest)
    dest_paths = materialize_agents(manifest, "claude", dest_root=tmp_path)

    assert len(dest_paths) == 0
    assert not (tmp_path / ".claude" / "agents").exists()


def test_materialize_idempotent(sample_agent_manifest: Path, tmp_path: Path) -> None:
    manifest_content = sample_agent_manifest.read_text(encoding="utf-8").replace(
        ".codex/agents/verify-implement.md",
        ".codex/agents/verify-implement.toml",
    ).replace(
        ".codex/agents/explorer.md",
        ".codex/agents/explorer.toml",
    )
    sample_agent_manifest.write_text(manifest_content, encoding="utf-8")
    manifest = load_manifest(sample_agent_manifest)
    first_run = materialize_agents(manifest, "codex", dest_root=tmp_path, repo_root=tmp_path)
    second_run = materialize_agents(manifest, "codex", dest_root=tmp_path, repo_root=tmp_path)

    assert first_run == second_run
    target_file = tmp_path / ".codex" / "agents" / "verify-implement.toml"
    assert 'name = "verify-implement"' in target_file.read_text(encoding="utf-8")
