from __future__ import annotations

import uuid
from dataclasses import replace
from typing import Any

from .boundary import BoundaryService
from .index import Queue, load_queue, phase_artifacts, prepare_step_status, qa_verdict
from .model import Cursor, CursorStatus, FailureRecord, Transition
from .store import CommitResult, LoopPaths, StoreTransaction, TransactionPlan, CursorStore
from .verdict import GateVerdict, MANAGED_GATE_AGENTS


class TransitionError(RuntimeError):
    pass


class LoopEngine:
    """The domain facade; CursorStore owns every state mutation."""

    def __init__(self, paths: LoopPaths):
        self.paths = paths
        self.store = CursorStore(paths)
        self.boundary = BoundaryService(paths)

    def _queue(self, cursor: Cursor) -> Queue:
        return load_queue(self.paths.project, cursor.role, cursor.epic_id)

    def _phase_after_queue(self, queue: Queue) -> tuple[str, str]:
        audit = phase_artifacts(self.paths.project, queue.role, queue.epic_id, "audit")
        qa = phase_artifacts(self.paths.project, queue.role, queue.epic_id, "qa")
        bugfix = phase_artifacts(self.paths.project, queue.role, queue.epic_id, "bugfix")
        if not audit:
            return "AUDIT", "audit artifact required"
        if not qa:
            return "QA", "qa artifact required"
        verdict = qa_verdict(qa[-1])
        if verdict in {"fail", "failed", "blocked"}:
            if bugfix:
                return "QA", "bugfix exists; re-qa required"
            return "BUGFIX", "qa failed"
        if verdict in {"pass", "passed", "complete", "completed"}:
            return "DONE", "qa passed"
        return "QA", "qa verdict missing"

    def _target(self, cursor: Cursor, queue: Queue | None = None) -> tuple[str, str, str]:
        active_queue = queue or self._queue(cursor)
        if active_queue.pending:
            step = active_queue.pending[0]
            return "IMPLEMENT", step.step_id, f"pending step {step.step_id}"
        phase, reason = self._phase_after_queue(active_queue)
        return phase, phase, reason

    @staticmethod
    def _copy_cursor(cursor: Cursor) -> Cursor:
        return Cursor.from_dict(cursor.to_dict())

    @staticmethod
    def _queue_after_step(queue: Queue, step_id: str) -> Queue:
        return replace(
            queue,
            steps=tuple(
                replace(step, status="completed") if step.step_id == step_id else step
                for step in queue.steps
            ),
        )

    def _render_body(self, cursor: Cursor, queue: Queue | None = None) -> str:
        active_queue = queue or self._queue(cursor)
        lines = [
            "---",
            "schema: loop-generated-context/v1",
            f"role: {cursor.role.upper()}",
            f"mode: {cursor.phase}",
            f"epic_id: {cursor.epic_id}",
            f"step_id: {cursor.step_id}",
            f"phase_epoch: {cursor.phase_epoch}",
            f"state_revision: {cursor.revision + 1}",
            "generated: true",
            "---",
            "",
            "## load_now",
            f"1. {active_queue.path.relative_to(self.paths.project).as_posix()} — queue/status",
        ]
        if cursor.step_id and cursor.phase in {"IMPLEMENT", "TASK", "REFACTOR", "BUGFIX"}:
            step = next((item for item in active_queue.steps if item.step_id == cursor.step_id), None)
            if step and step.shard:
                lines.append(f"2. {step.shard} — current step artifact")
        lines.extend(
            [
                "",
                f"## Handoff {cursor.phase}",
                f"- Current cursor: `{cursor.epic_id}/{cursor.phase}/{cursor.step_id}`.",
                "- This file is generated by loop/kernel; do not edit it as state.",
                f"- Finish with: `python3 $DEV_HUB/bin/loop.py finish --project {self.paths.project} --step {cursor.step_id}`.",
                "",
                self.boundary.context(cursor),
            ]
        )
        return "\n".join(lines) + "\n"

    @staticmethod
    def _failure(category: str, code: str, message: str, *, retryable: bool, attempt: int, details: dict[str, Any] | None = None) -> FailureRecord:
        return FailureRecord(category, code, message, retryable, attempt, details=details or {})

    def _finish_plan(self, cursor: Cursor, transaction: StoreTransaction, *, step_id: str | None, reason: str, event: dict[str, Any]) -> TransactionPlan:
        if cursor.status == CursorStatus.COMPLETE:
            return TransactionPlan(cursor, {"event": "finish_duplicate", "reason": "already complete"}, changed=False)
        if cursor.status == CursorStatus.HALTED:
            raise TransitionError("cannot finish a halted cursor")
        if step_id and step_id != cursor.step_id:
            raise TransitionError(f"finish step mismatch: cursor={cursor.step_id}, received={step_id}")

        queue = self._queue(cursor)
        next_queue = queue
        mutations = []
        if cursor.phase in {"IMPLEMENT", "TASK", "REFACTOR"}:
            index_mutation = prepare_step_status(queue, cursor.step_id, "completed")
            mutations.append(index_mutation)
            next_queue = self._queue_after_step(queue, cursor.step_id)
        elif cursor.phase == "AUDIT":
            if not phase_artifacts(self.paths.project, queue.role, queue.epic_id, "audit"):
                raise TransitionError("cannot finish AUDIT without an audit artifact")
        elif cursor.phase == "QA":
            artifacts = phase_artifacts(self.paths.project, queue.role, queue.epic_id, "qa")
            verdict = qa_verdict(artifacts[-1]) if artifacts else None
            if verdict not in {"fail", "failed", "blocked", "pass", "passed", "complete", "completed"}:
                raise TransitionError("cannot finish QA without a valid verdict")
        elif cursor.phase == "BUGFIX":
            if not phase_artifacts(self.paths.project, queue.role, queue.epic_id, "bugfix"):
                raise TransitionError("cannot finish BUGFIX without a bugfix artifact")

        phase, next_step, target_reason = self._target(cursor, next_queue)
        candidate = self._copy_cursor(cursor)
        candidate.phase, candidate.step_id = phase, next_step
        candidate.status = CursorStatus.COMPLETE if phase == "DONE" else CursorStatus.ACTIVE
        candidate.attempt = 0
        candidate.failure = None
        candidate.phase_epoch += 1
        mutations.append(transaction.mutation(self.paths.active_context, self._render_body(candidate, next_queue)))
        transition_event = {
            **event,
            "reason": reason,
            "source_phase": cursor.phase,
            "source_step_id": cursor.step_id,
            "phase": phase,
            "step_id": next_step,
            "target_reason": target_reason,
        }
        return TransactionPlan(candidate, transition_event, tuple(mutations))

    def start(self, epic_id: str, role: str = "back") -> Cursor:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current and current.status in {CursorStatus.ACTIVE, CursorStatus.RETRY}:
                if current.epic_id != epic_id or current.role != role:
                    raise TransitionError("cursor already owns another epic; finish or halt it first")
                return TransactionPlan(current, {"event": "start_duplicate"}, changed=False)
            candidate = Cursor(
                epic_id=epic_id,
                role=role,
                session_id=f"session-{uuid.uuid4().hex[:12]}",
                phase_epoch=1,
            )
            phase, step, reason = self._target(candidate)
            candidate.phase, candidate.step_id = phase, step
            candidate.status = CursorStatus.COMPLETE if phase == "DONE" else CursorStatus.ACTIVE
            return TransactionPlan(
                candidate,
                {"event": "start", "epic_id": epic_id, "role": role, "phase": phase, "step_id": step, "reason": reason},
                (transaction.mutation(self.paths.active_context, self._render_body(candidate)),),
            )

        result = self.store.transact(planner)
        if result.cursor is None:
            raise TransitionError("start transaction did not produce a cursor")
        return result.cursor

    def _transition_from_result(self, result: CommitResult, *, event: str, reason: str, metadata: dict[str, Any] | None = None) -> Transition:
        cursor = result.cursor
        if cursor is None:
            raise TransitionError("transaction did not return cursor")
        return Transition(
            event,
            reason,
            cursor.phase,
            cursor.step_id,
            cursor.status,
            cursor.attempt,
            result.changed,
            metadata or {},
            cursor.revision,
            result.tx_id,
        )

    def finish(self, *, step_id: str | None = None, reason: str = "session completed") -> Transition:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current is None:
                raise TransitionError("cursor does not exist; run start first")
            return self._finish_plan(current, transaction, step_id=step_id, reason=reason, event={"event": "finish"})

        result = self.store.transact(planner)
        return self._transition_from_result(result, event=str(result.event.get("event") or "finish"), reason=str(result.event.get("reason") or reason))

    def accept_verdict(self, record: GateVerdict, *, source: str = "subagent-stop", expected_agent_id: str | None = None) -> Transition:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current is None:
                raise TransitionError("cursor does not exist; run start first")
            key = f"{record.session_id}:{record.epic_id}:{record.step_id}:{record.agent_id}:{record.verdict}"
            if transaction.event_seen("verdict_accepted", key) or transaction.event_seen("verdict_recorded", key):
                return TransactionPlan(current, {"event": "verdict_duplicate", "key": key}, changed=False)
            if record.agent_id not in MANAGED_GATE_AGENTS:
                raise TransitionError(f"unsupported gate agent: {record.agent_id}")
            if expected_agent_id and record.agent_id != expected_agent_id:
                raise TransitionError(f"verdict agent mismatch: expected={expected_agent_id}, received={record.agent_id}")
            if current.epic_id != record.epic_id:
                raise TransitionError(f"verdict epic mismatch: cursor={current.epic_id}, received={record.epic_id}")
            if current.session_id != record.session_id:
                raise TransitionError("verdict session mismatch")
            if current.step_id != record.step_id:
                raise TransitionError(f"verdict step mismatch: cursor={current.step_id}, received={record.step_id}")
            event = {
                "event": "verdict_accepted" if record.verdict == "PASS" else "verdict_recorded",
                "key": key,
                "source": source,
                "agent_id": record.agent_id,
                "verdict": record.verdict,
                "recorded_at": record.recorded_at,
                "evidence_sha256": record.evidence_sha256,
            }
            if record.verdict != "PASS":
                return TransactionPlan(None, event)
            return self._finish_plan(current, transaction, step_id=record.step_id, reason=f"{source}:{record.agent_id}:PASS", event=event)

        result = self.store.transact(planner)
        return self._transition_from_result(
            result,
            event=str(result.event.get("event") or "verdict_recorded"),
            reason=str(result.event.get("reason") or result.event.get("verdict") or "verdict"),
            metadata={"key": result.event.get("key"), "agent_id": result.event.get("agent_id"), "verdict": result.event.get("verdict")},
        )

    def reject_verdict(self, *, agent_id: str, diagnostic_codes: list[str] | tuple[str, ...], errors: list[str] | tuple[str, ...], source: str = "subagent-stop", max_retries: int = 2) -> tuple[int, bool]:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current is None:
                raise TransitionError("cannot reject a verdict without a cursor")
            prefix = f"{current.session_id}:{current.epic_id}:{current.step_id}:{agent_id}:"
            retry_number = transaction.event_count("verdict_rejected", prefix) + 1
            rejection = {
                "event": "verdict_rejected",
                "key": f"{prefix}{retry_number}",
                "source": source,
                "agent_id": agent_id,
                "phase": current.phase,
                "step_id": current.step_id,
                "retry": retry_number,
                "diagnostic_codes": list(diagnostic_codes),
                "errors": list(errors),
            }
            if retry_number <= max_retries:
                return TransactionPlan(None, rejection)
            candidate = self._copy_cursor(current)
            reason = f"schema_retry_exhausted:{agent_id}"
            candidate.status = CursorStatus.HALTED
            candidate.failure = self._failure("boundary", "schema_retry_exhausted", reason, retryable=False, attempt=candidate.attempt, details={"agent_id": agent_id})
            halt = {"event": "halt", "reason": reason, "phase": current.phase, "step_id": current.step_id}
            mutations = (transaction.mutation(self.paths.active_context, self._render_body(candidate)),)
            return TransactionPlan(candidate, halt, mutations, (rejection,))

        result = self.store.transact(planner)
        retry_number = int(result.event.get("retry") or max_retries + 1)
        return retry_number, bool(result.cursor and result.cursor.status == CursorStatus.HALTED)

    def record_event(self, event: dict[str, Any]) -> None:
        self.store.record_event(event)

    def retry(self, reason: str, *, expected_revision: int | None = None, details: dict[str, Any] | None = None) -> Transition:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current is None:
                raise TransitionError("cannot retry without cursor")
            if expected_revision is not None and current.revision != expected_revision:
                return TransactionPlan(current, {"event": "retry_skipped", "reason": "cursor advanced externally"}, changed=False)
            if current.status == CursorStatus.COMPLETE:
                raise TransitionError("cannot retry a complete cursor")
            if current.status == CursorStatus.HALTED:
                raise TransitionError("cannot retry a halted cursor")
            candidate = self._copy_cursor(current)
            candidate.status = CursorStatus.RETRY
            candidate.attempt += 1
            candidate.failure = self._failure("session", "retry", reason, retryable=True, attempt=candidate.attempt, details=details)
            return TransactionPlan(
                candidate,
                {"event": "retry", "reason": reason, "phase": candidate.phase, "step_id": candidate.step_id, "attempt": candidate.attempt},
                (transaction.mutation(self.paths.active_context, self._render_body(candidate)),),
            )

        result = self.store.transact(planner)
        return self._transition_from_result(result, event=str(result.event.get("event") or "retry"), reason=str(result.event.get("reason") or reason))

    def halt(
        self,
        reason: str,
        *,
        expected_revision: int | None = None,
        details: dict[str, Any] | None = None,
        failure_category: str = "operator",
        failure_code: str = "halt",
    ) -> Transition:
        def planner(current: Cursor | None, transaction: StoreTransaction) -> TransactionPlan:
            if current is None:
                raise TransitionError("cannot halt without cursor")
            if expected_revision is not None and current.revision != expected_revision:
                return TransactionPlan(current, {"event": "halt_skipped", "reason": "cursor advanced externally"}, changed=False)
            if current.status == CursorStatus.HALTED:
                return TransactionPlan(current, {"event": "halt_duplicate", "reason": reason}, changed=False)
            candidate = self._copy_cursor(current)
            candidate.status = CursorStatus.HALTED
            candidate.failure = self._failure(failure_category, failure_code, reason, retryable=False, attempt=candidate.attempt, details=details)
            return TransactionPlan(
                candidate,
                {"event": "halt", "reason": reason, "phase": candidate.phase, "step_id": candidate.step_id},
                (transaction.mutation(self.paths.active_context, self._render_body(candidate)),),
            )

        result = self.store.transact(planner)
        return self._transition_from_result(result, event=str(result.event.get("event") or "halt"), reason=reason)

    def status(self) -> dict[str, Any]:
        cursor = self.store.read()
        if cursor is None:
            return {"ok": True, "status": "uninitialized", "cursor": None, "cursor_path": str(self.paths.cursor)}
        return {"ok": True, "status": cursor.status.value, "cursor": cursor.to_dict(), "cursor_path": str(self.paths.cursor)}

    def doctor(self) -> dict[str, Any]:
        result: dict[str, Any] = {"ok": True, "cursor_path": str(self.paths.cursor), "active_context": str(self.paths.active_context), "journal_path": str(self.paths.events)}
        try:
            cursor = self.store.read()
            result["cursor"] = cursor.to_dict() if cursor else None
            if cursor:
                queue = self._queue(cursor)
                result["index"] = str(queue.path)
                result["pending_steps"] = [step.step_id for step in queue.pending]
        except Exception as exc:
            result.update({"ok": False, "error": str(exc)})
        return result
