#!/usr/bin/env bash
# Context-first loop — канон: memory-bank/activeContext.md (+ index/shard).
# Runner: сессии + transient API retry. Курсор и переходы = activeContext.
# EPIC arg: overwrite activeContext from decompose index (manual epic switch).
# Mode arg: optional session mode (currently implement).
set -euo pipefail

_LOOP_SOURCE_ARGS=("$@")

HUB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export DEV_HUB="$HUB_ROOT"
export HUB_ROOT

if [[ -z "${PROJECT_ROOT:-}" ]]; then
  echo "==> ERROR: PROJECT_ROOT required (product repo with memory-bank/)" >&2
  echo "    Example: PROJECT_ROOT=/home/aero/PyProject/job-autopilot $HUB_ROOT/bin/loop gpt" >&2
  exit 2
fi
PROJECT_ROOT="$(cd "$PROJECT_ROOT" && pwd)"
export PROJECT_ROOT
# Canonical contract alias for FR-009 project root compatibility
export EPIC_PROJECT_ROOT="$PROJECT_ROOT"
PROJ_SLUG="$(basename "$PROJECT_ROOT")"
# Runner scripts use absolute PROJECT_ROOT; Claude session cwd = hub (agents/settings).
cd "$HUB_ROOT"
export CLAUDE_PROJECT_DIR="$HUB_ROOT"
export EPIC_LOOP=1

# Hub .claude/project.env[.local] (+ optional projects/<slug>/project.env*) → export
_PROJECT_ENV_EXPORTS="$(
  python3 -c "
import sys
sys.path.insert(0, r'$HUB_ROOT/harness/hooks')
from _lib import bash_exports_project_env
print(bash_exports_project_env(r'$HUB_ROOT'))
" 2>/dev/null || true
)"
if [[ -n "${_PROJECT_ENV_EXPORTS}" ]]; then
  eval "${_PROJECT_ENV_EXPORTS}"
  if [[ "${EPIC_VERBOSE_ENV:-0}" == "1" ]]; then
    echo "==> loaded hub .claude/project.env exports" >&2
  fi
fi
unset _PROJECT_ENV_EXPORTS

configure_runtime_env() {
  local runtime="${1:-${EPIC_RUNTIME:-${EPIC_RUNTIME_RESOLVED:-claude}}}"
  if [[ "$runtime" == "dsh" ]]; then
    export DSH_HOOKS_BRIDGE=1
    export CLAUDE_PROJECT_DIR="$PROJECT_ROOT"
  else
    unset DSH_HOOKS_BRIDGE
    export CLAUDE_PROJECT_DIR="$HUB_ROOT"
  fi
}
configure_runtime_env

# Extension sets CLAUDE_CODE_ENABLE_TASKS=0; without it Gemini/Omniroute often 429s.
export CLAUDE_CODE_ENABLE_TASKS="${CLAUDE_CODE_ENABLE_TASKS:-0}"

HARNESS_HOOKS="$HUB_ROOT/harness/hooks"
CTX=(python3 "$HUB_ROOT/loop/context_loop.py" --cwd "$PROJECT_ROOT")
STATE_DIR="$HUB_ROOT/runtime/$PROJ_SLUG/epic"
STREAM_FILTER="$HARNESS_HOOKS/epic_stream_filter.py"
CODEX_STREAM_FILTER="$HARNESS_HOOKS/epic_codex_stream_filter.py"
ROOT="$HUB_ROOT"
SESSION_WRAPPER="$HARNESS_HOOKS/session_resilience.py"
mkdir -p "$STATE_DIR"

_runtime_config_json="$({
  python3 - "$HUB_ROOT" <<'PY'
import json
import sys
sys.path.insert(0, sys.argv[1] + "/harness/hooks")
from _lib import resolve_runtime_config, runtime_config_status

try:
    print(json.dumps(runtime_config_status(resolve_runtime_config(sys.argv[1])), ensure_ascii=False))
except Exception as exc:
    print(json.dumps({"code": "invalid_runtime_config", "diagnostics": getattr(exc, "diagnostics", [])}, ensure_ascii=False))
    raise SystemExit(2)
PY
})" || {
  echo "==> ERROR: invalid_runtime_config $_runtime_config_json" >&2
  exit 2
}
export EPIC_SESSION_TIMEOUT_SEC="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_SESSION_TIMEOUT_SEC"])')"
export EPIC_SESSION_KILL_GRACE_SEC="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_SESSION_KILL_GRACE_SEC"])')"
export EPIC_TRANSIENT_RETRY_MAX="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_TRANSIENT_RETRY_MAX"])')"
export EPIC_DEGRADED_MAX="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_DEGRADED_MAX"])')"
export EPIC_STATUS_HEARTBEAT_SEC="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_STATUS_HEARTBEAT_SEC"] or "")')"
export EPIC_STREAM_IDLE_TIMEOUT_SEC="$(printf '%s' "$_runtime_config_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["effective"]["EPIC_STREAM_IDLE_TIMEOUT_SEC"] or "")')"

_runtime_owner_path="$STATE_DIR/runner.json"
_runtime_session_id="$(python3 -c 'import uuid; print(uuid.uuid4())')"
_runtime_started_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
# Stable across Claude invoke retries / session aborts within this loop process.
# Hooks + prepare bind verify evidence to this id (not Claude's per-try session).
export EPIC_RUNNER_SESSION_ID="$_runtime_session_id"

# One runner per checkout; acquire the lock before publishing runner ownership.
exec 9>"$STATE_DIR/runner.lock"
if ! flock -n 9; then
  echo "==> ERROR: another loop runner is already active" >&2
  exit 1
fi

_runtime_status_json="$_runtime_config_json"
export EPIC_RUNTIME_CONFIG_JSON="$_runtime_config_json"

_clean_pycache() {
  rm -rf "$HUB_ROOT/harness/hooks/__pycache__" "$HUB_ROOT/loop/__pycache__"
}

# Remove generated bytecode before the py_compile smoke check; source files are the only runtime artifacts.
_clean_pycache

for _hf in \
  "$HUB_ROOT/loop/context_loop.py" \
  "$HARNESS_HOOKS/session_resilience.py" \
  "$HARNESS_HOOKS/epic_lib.py" \
  "$HARNESS_HOOKS/stop-gate.py"
do
  if ! python3 -m py_compile "$_hf" >/dev/null 2>&1; then
    echo "==> loop smoke FAIL: does not compile: $_hf" >&2
    python3 -m py_compile "$_hf" >&2 || true
    exit 2
  fi
done

usage() {
  cat <<'EOF'
Usage: ./loop/loop.sh [EPIC] [MODEL] [MODE] [options]

Context-first автоцикл. Курсор = memory-bank/activeContext.md.

EPIC (опционально): T-HUB-027 | plan-<epic>.md | decompose-<id> | memory-bank/.../plan/...
  → arm via resolver (PLAN / DECOMPOSE / ANALYZE / IMPLEMENT по состоянию эпика).
  → Прошлый activeContext игнорируется.
Без EPIC: продолжение с текущего activeContext.

Examples:
  ./bin/loop . gpt
  ./bin/loop . --epic T-HUB-027 agy/gemini-3.6-flash-medium
  ./bin/loop . plan-T-HUB-027-back-plan-gstack-adapt.md agy/gemini-3.6-flash-medium
  ./bin/loop . decompose-v1-portal gpt implement

MODE:
  implement
      Force the activeContext cursor to run an IMPLEMENT step.
  ./loop/loop.sh --status

Options:
  --epic EPIC_ID
      Arm epic via arm_epic (e.g. T-HUB-016).
  -m, --model NAME
      --phase GAP_FANOUT
          Arm the next dependency-ready epic from loop/dag/*.yaml.
      --dag-generate PIPELINE
          Generate a DAG manifest from memory-bank/integration/gap/.
      --permission-mode MODE
      --interactive | --headless
      --verbose
      --status
  -h, --help
EOF
}

find_claude() {
  if [[ -n "${CLAUDE_BIN:-}" && -x "$CLAUDE_BIN" ]]; then
    echo "$CLAUDE_BIN"
    return
  fi
  if command -v claude >/dev/null 2>&1; then
    command -v claude
    return
  fi
  local cand
  cand="$(ls -1d "$HOME"/.cursor/extensions/anthropic.claude-code-*/resources/native-binary/claude 2>/dev/null | sort -V | tail -1 || true)"
  if [[ -n "$cand" && -x "$cand" ]]; then
    echo "$cand"
    return
  fi
  echo "claude binary not found; set CLAUDE_BIN" >&2
  exit 127
}

is_epic_spec() {
  case "$1" in
    decompose-*|plan-*|T-*)
      return 0 ;;
    memory-bank/*/plan/decompose-*|memory-bank/*/plan/plan-*)
      return 0 ;;
    memory-bank/*/plan/decompose-*/index.md)
      return 0 ;;
    */decompose-*|*/plan-*)
      return 0 ;;
    *)
      return 1 ;;
  esac
}

MODEL=""
EPIC_SPEC=""
EPIC_ID_FLAG=""
MODE=""
PERM_MODE="${EPIC_PERMISSION_MODE:-dontAsk}"
HEADLESS=1
INTERACTIVE=0
VERBOSE=0
DO_STATUS=0
DO_FANOUT=0
PIPELINE_ID=""
GENERATE_DAG=0
DAG_PIPELINE=""
EXTRA_ARGS=()
POSITIONAL=()
# shellcheck disable=SC2206
[[ -n "${EPIC_CLAUDE_ARGS:-}" ]] && EXTRA_ARGS=( ${EPIC_CLAUDE_ARGS} )

while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help) usage; exit 0 ;;
    --status) DO_STATUS=1; shift ;;
    --gap-fanout|--phase)
      if [[ "$1" == "--phase" ]]; then
        [[ $# -ge 2 ]] || { echo "missing value for --phase" >&2; exit 2; }
        [[ "$2" == "GAP_FANOUT" ]] || { echo "unsupported phase: $2" >&2; exit 2; }
        shift 2
      else
        shift
      fi
      DO_FANOUT=1 ;;
    --dag-generate)
      [[ $# -ge 2 ]] || { echo "missing value for --dag-generate" >&2; exit 2; }
      GENERATE_DAG=1; DAG_PIPELINE="$2"; shift 2 ;;
    --epic)
      [[ $# -ge 2 ]] || { echo "missing value for --epic" >&2; exit 2; }
      EPIC_ID_FLAG="$2"; shift 2 ;;
    -m|--model)
      [[ $# -ge 2 ]] || { echo "missing value for $1" >&2; exit 2; }
      MODEL="$2"; shift 2 ;;
    --permission-mode)
      [[ $# -ge 2 ]] || { echo "missing value for $1" >&2; exit 2; }
      PERM_MODE="$2"; shift 2 ;;
    --headless) HEADLESS=1; INTERACTIVE=0; shift ;;
    --interactive) INTERACTIVE=1; HEADLESS=0; shift ;;
    --verbose) VERBOSE=1; shift ;;
    --)
      shift; EXTRA_ARGS+=("$@"); break ;;
    -*)
      echo "unknown option: $1" >&2; usage >&2; exit 2 ;;
    *)
      POSITIONAL+=("$1"); shift ;;
  esac
done

for _p in "${POSITIONAL[@]+"${POSITIONAL[@]}"}"; do
  if is_epic_spec "$_p"; then
    if [[ -n "$EPIC_SPEC" ]]; then
      echo "==> ERROR: multiple epic specs: '$EPIC_SPEC' and '$_p'" >&2
      exit 2
    fi
    EPIC_SPEC="$_p"
    continue
  fi
  if [[ -z "$MODEL" ]]; then
    MODEL="$_p"
    continue
  fi
  if [[ -z "$MODE" && "$_p" == "implement" ]]; then
    MODE="$_p"
    continue
  fi
  echo "==> ERROR: unexpected positional argument '$_p' (expected MODE=implement)" >&2
  usage >&2
  exit 2
done

if [[ -n "$MODE" ]]; then
  echo "==> mode=$MODE (forced activeContext IMPLEMENT cursor)"
fi
if [[ -n "$MODE" && -z "$EPIC_SPEC" ]]; then
  echo "==> ERROR: MODE=$MODE requires an EPIC spec to select the activeContext cursor" >&2
  exit 2
fi
if [[ -n "$MODE" && -z "$MODEL" ]]; then
  echo "==> ERROR: MODE=$MODE requires a MODEL" >&2
  exit 2
fi

python3 - "$HUB_ROOT" "$STATE_DIR" "$_runtime_session_id" "$_runtime_started_at" "${MODEL:-}" "${MODE:-}" "$$" <<'PY'
import os
import socket
import sys
from pathlib import Path
sys.path.insert(0, str(Path(sys.argv[1]) / "harness/hooks"))
from _lib import RunnerOwner, write_runner_owner

state_dir = Path(sys.argv[2])
write_runner_owner(
    state_dir / "runner.json",
    RunnerOwner(
        pid=int(sys.argv[7]),
        host=socket.gethostname(),
        started_at=sys.argv[4],
        session_id=sys.argv[3],
        selected_identity="BACK IMPLEMENT" if sys.argv[6] == "implement" else "",
        mode=sys.argv[6],
        model=sys.argv[5],
        timeout_config={
            "session_timeout_sec": int(os.environ["EPIC_SESSION_TIMEOUT_SEC"]),
            "kill_grace_sec": int(os.environ["EPIC_SESSION_KILL_GRACE_SEC"]),
        },
    ),
)
PY
_cleanup_runner_owner() {
  python3 - "$HUB_ROOT" "$STATE_DIR" "$_runtime_session_id" "$$" <<'PY'
import sys
from pathlib import Path
sys.path.insert(0, str(Path(sys.argv[1]) / "harness/hooks"))
from _lib import remove_runner_owner_if_owned
remove_runner_owner_if_owned(
    Path(sys.argv[2]) / "runner.json",
    int(sys.argv[4]),
    sys.argv[3],
)
PY
}
_exit_loop_user_interrupt() {
  echo "==> LOOP STOPPED (Ctrl+C)" >&2
  exit 130
}
_on_user_interrupt() {
  _exit_loop_user_interrupt
}
trap _on_user_interrupt INT
trap _cleanup_runner_owner EXIT HUP TERM

if [[ "$DO_STATUS" == "1" ]]; then
  "${CTX[@]}" status
  exit 0
fi

if [[ "$GENERATE_DAG" == "1" ]]; then
  "${CTX[@]}" dag-generate --pipeline "$DAG_PIPELINE"
  exit $?
fi

if [[ "$DO_FANOUT" == "1" ]]; then
  set +e
  fanout_json="$("${CTX[@]}" dag-fanout)"
  fanout_rc=$?
  set -e
  printf '%s\n' "$fanout_json"
  exit "$fanout_rc"
fi

if [[ "${EPIC_LOOP_DOCTOR_PREFLIGHT:-0}" == "1" ]]; then
  echo "==> doctor preflight (EPIC_LOOP_DOCTOR_PREFLIGHT=1)"
  set +e
  "${CTX[@]}" doctor
  doc_rc=$?
  set -e
  if [[ $doc_rc -ne 0 ]]; then
    echo "==> ERROR: doctor preflight failed (rc=$doc_rc)" >&2
    exit "$doc_rc"
  fi
fi

CLAUDE="$(find_claude)"
PERM_ARGS=(--permission-mode "$PERM_MODE")
# MODEL_ARGS rebuilt each session from prepare (phase override → CLI MODEL).
MODEL_ARGS=()
[[ -n "$MODEL" ]] && MODEL_ARGS=(--model "$MODEL")

if [[ -n "$EPIC_ID_FLAG" ]]; then
  echo "==> arm epic=$EPIC_ID_FLAG (arm_epic via resolver)"
  set +e
  arm_json="$("${CTX[@]}" arm --epic "$EPIC_ID_FLAG")"
  arm_rc=$?
  set -e
  if [[ "$VERBOSE" == "1" ]]; then
    echo "$arm_json"
  else
    echo "$arm_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
if r.get("ok"):
    if r.get("complete"):
        print("==> arm:", r.get("stop") or "complete", "epic=", r.get("epic_id"))
    else:
        print("==> arm ok:", r.get("role"), r.get("epic_id"),
              "step=", r.get("step_id"), "phase=", r.get("phase"))
        if r.get("work_shard"): print("==> work_shard:", r["work_shard"])
else:
    print("==> arm FAIL:", r.get("error") or r)
' 2>/dev/null || echo "$arm_json"
  fi
  if [[ $arm_rc -eq 3 ]]; then
    echo "==> LOOP COMPLETE (epic already done)"
    exit 0
  fi
  if [[ $arm_rc -ne 0 ]]; then
    echo "==> LOOP HALTED (arm)" >&2
    exit "$arm_rc"
  fi
elif [[ -n "$EPIC_SPEC" ]]; then
  echo "==> arm epic=$EPIC_SPEC (arm_epic via resolver)"
  set +e
  arm_json="$("${CTX[@]}" arm --epic "$EPIC_SPEC")"
  arm_rc=$?
  set -e
  if [[ "$VERBOSE" == "1" ]]; then
    echo "$arm_json"
  else
    echo "$arm_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
if r.get("ok"):
    if r.get("complete"):
        print("==> arm:", r.get("stop") or "complete", "epic=", r.get("epic_id"))
    else:
        print("==> arm ok:", r.get("role"), r.get("epic_id"),
              "step=", r.get("step_id"), "phase=", r.get("phase"))
        if r.get("work_shard"): print("==> work_shard:", r["work_shard"])
else:
    print("==> arm FAIL:", r.get("error") or r)
' 2>/dev/null || echo "$arm_json"
  fi
  if [[ $arm_rc -eq 3 ]]; then
    echo "==> LOOP COMPLETE (epic already done)"
    exit 0
  fi
  if [[ $arm_rc -ne 0 ]]; then
    echo "==> LOOP HALTED (arm)" >&2
    exit "$arm_rc"
  fi
fi

run_claude_session() {
  local iter="$1"
  local prompt_file="$2"
  local log_file="$STATE_DIR/session-${iter}.log"
  local prompt
  prompt="$(cat "$prompt_file")"

  local mode=headless
  local -a command
  # Claude loads .claude/agents+settings from cwd=hub; product code via --add-dir.
  local -a add_dir_args=(--add-dir "$PROJECT_ROOT")
  if [[ "$HEADLESS" == "1" ]]; then
    echo "==> headless → $log_file (claude cwd=$HUB_ROOT add-dir=$PROJECT_ROOT)"
    # IMPORTANT: prompt must follow -p immediately. --add-dir is variadic and
    # would swallow the prompt text as another "directory" if placed before it.
    command=("$CLAUDE" -p "$prompt" \
      --output-format stream-json \
      --include-partial-messages \
      --verbose \
      "${add_dir_args[@]}" \
      "${PERM_ARGS[@]}" "${MODEL_ARGS[@]}" "${EXTRA_ARGS[@]}")
  else
    mode=interactive
    echo "==> interactive — /exit after FINISH (claude cwd=$HUB_ROOT add-dir=$PROJECT_ROOT)"
    command=("$CLAUDE" "$prompt" "${add_dir_args[@]}" "${PERM_ARGS[@]}" "${MODEL_ARGS[@]}" "${EXTRA_ARGS[@]}")
  fi

  set +e
  if [[ "$HEADLESS" == "1" ]]; then
    (cd "$HUB_ROOT" && python3 "$SESSION_WRAPPER" run-session \
      --mode "$mode" \
      --session-id "$iter" \
      --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
      --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
      ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
      ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
      --log "$log_file" \
      ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
      -- "${command[@]}") | python3 "$STREAM_FILTER"
    rc="${PIPESTATUS[0]}"
  else
    (cd "$HUB_ROOT" && python3 "$SESSION_WRAPPER" run-session \
      --mode "$mode" \
      --session-id "$iter" \
      --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
      --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
      ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
      ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
      --log "$log_file" \
      ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
      -- "${command[@]}")
    rc=$?
  fi
  # HARD: do NOT `set -e` before return — under bash errexit a non-zero
  # `return` from a function aborts the whole loop.sh (skips record-session /
  # transient retry). Caller owns set +e / set -e around this call.
  return "$rc"
}

resolve_dsh_bin() {
  if [[ -n "${DSH_BIN:-}" && -x "$DSH_BIN" ]]; then
    DSH_COMMAND=("$DSH_BIN")
    return 0
  fi

  local resolver="${DSH_RESOLVER:-$HUB_ROOT/dsh/bin/which-dsh.sh}"
  if [[ -x "$resolver" ]]; then
    local -a resolved
    local executable
    mapfile -t resolved < <("$resolver")
    if [[ ${#resolved[@]} -gt 0 ]]; then
      executable="${resolved[0]}"
      if [[ "$executable" != */* ]]; then
        executable="$(command -v "$executable" || true)"
      fi
      if [[ -n "$executable" && -x "$executable" ]]; then
        DSH_COMMAND=("$executable" "${resolved[@]:1}")
        return 0
      fi
      echo "dsh binary not found: ${resolved[*]}" >&2
      return 127
    fi
  fi

  echo "dsh binary not found; set DSH_BIN or install @deepseek-ai/dsh" >&2
  return 127
}

DSH_COMMAND=()


run_dsh_session() {
  local iter="$1"
  local prompt_file="$2"
  local log_file="$STATE_DIR/session-${iter}.log"
  local prompt
  local dsh_rc
  prompt="$(cat "$prompt_file")"

  if resolve_dsh_bin; then
    dsh_rc=0
  else
    dsh_rc=$?
  fi
  if [[ $dsh_rc -ne 0 || ${#DSH_COMMAND[@]} -eq 0 ]]; then
    echo "==> HALT: dsh binary not found; no Claude fallback" >&2
    return 127
  fi

  local profile_override
  profile_override="$(echo "${EXTRAS_JSON:-{}}" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("dsh_profile") or "epic-implement")' 2>/dev/null || echo epic-implement)"
  local profile="$profile_override"
  local -a command=("${DSH_COMMAND[@]}" --profile "$profile" --no-open "$prompt")
  local rc
  if (cd "$PROJECT_ROOT" && python3 "$SESSION_WRAPPER" run-session \
    --mode headless \
    --session-id "$iter" \
    --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
    --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
    ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
    ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
    --log "$log_file" \
    -- "${command[@]}"); then
    rc=0
  else
    rc=$?
  fi
  return "$rc"
}

run_agent_session() {
  local iter="$1"
  local prompt_file="$2"
  local log_file="$STATE_DIR/session-${iter}.log"
  local runtime_id="${EPIC_RUNTIME_RESOLVED:-claude}"
  local extras_json="{}"
  local -a command=()
  local rc=0
  local session_cwd="$HUB_ROOT"

  if [[ "$runtime_id" == "dsh" ]]; then
    extras_json="${EXTRAS_JSON:-{}}"
    session_cwd="$PROJECT_ROOT"
  elif [[ "$runtime_id" == "codex" ]]; then
    extras_json="$(PROJECT_ROOT="$PROJECT_ROOT" python3 -c 'import json,os; print(json.dumps({"project_root": os.environ["PROJECT_ROOT"]}))')"
    session_cwd="$PROJECT_ROOT"
  fi

  local argv_json=""
  argv_json="$(python3 -m loop.runtime.dispatch print-argv \
    --runtime "$runtime_id" \
    --prompt-file "$prompt_file" \
    --phase "${LOOP_PHASE:-IMPLEMENT}" \
    ${SESSION_MODEL:+--model "$SESSION_MODEL"} \
    --extras-json "$extras_json")" || {
    echo "==> HALT: dispatch print-argv failed for runtime=$runtime_id" >&2
    return 2
  }
  if [[ -z "$argv_json" ]]; then
    echo "==> HALT: dispatch print-argv empty for runtime=$runtime_id" >&2
    return 2
  fi
  mapfile -d '' -t command < <(printf '%s' "$argv_json" | python3 -c '
import json, sys
for part in json.load(sys.stdin):
    sys.stdout.buffer.write(part.encode("utf-8") + b"\0")
')

  if [[ "$runtime_id" == "claude" ]]; then
    command[0]="$CLAUDE"
    command+=("--add-dir" "$PROJECT_ROOT")
    command+=("${PERM_ARGS[@]}" "${EXTRA_ARGS[@]}")
  elif [[ "$runtime_id" == "dsh" ]]; then
    if ! resolve_dsh_bin; then
      echo "==> HALT: dsh binary not found; no Claude fallback" >&2
      return 127
    fi
    command=("${DSH_COMMAND[@]}" "${command[@]:1}")
  fi

  local -a stdin_file_args=()
  local progress_mode="tool_json"
  if [[ "$runtime_id" == "codex" ]]; then
    stdin_file_args=(--stdin-file "$prompt_file")
    progress_mode="codex_json"
  fi

  set +e
  if [[ "$HEADLESS" == "1" ]]; then
    echo "==> headless → $log_file (runtime=$runtime_id cwd=$session_cwd)"
    if [[ "$runtime_id" == "claude" ]]; then
      (cd "$session_cwd" && python3 "$SESSION_WRAPPER" run-session \
        --mode headless \
        --session-id "$iter" \
        --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
        --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
        ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
        ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
        --progress-mode "$progress_mode" \
        --log "$log_file" \
        ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
        -- "${command[@]}") | python3 "$STREAM_FILTER"
      rc="${PIPESTATUS[0]}"
    elif [[ "$runtime_id" == "codex" ]]; then
      (cd "$session_cwd" && python3 "$SESSION_WRAPPER" run-session \
        --mode headless \
        --session-id "$iter" \
        --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
        --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
        ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
        ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
        --progress-mode "$progress_mode" \
        --log "$log_file" \
        ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
        "${stdin_file_args[@]}" \
        -- "${command[@]}") | python3 "$CODEX_STREAM_FILTER"
      rc="${PIPESTATUS[0]}"
    else
      (cd "$session_cwd" && python3 "$SESSION_WRAPPER" run-session \
        --mode headless \
        --session-id "$iter" \
        --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
        --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
        ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
        ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
        --progress-mode "$progress_mode" \
        --log "$log_file" \
        ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
        "${stdin_file_args[@]}" \
        -- "${command[@]}")
      rc=$?
    fi
  else
    echo "==> interactive — /exit after FINISH (runtime=$runtime_id cwd=$session_cwd)"
    (cd "$session_cwd" && python3 "$SESSION_WRAPPER" run-session \
      --mode interactive \
      --session-id "$iter" \
      --timeout "$EPIC_SESSION_TIMEOUT_SEC" \
      --kill-grace "$EPIC_SESSION_KILL_GRACE_SEC" \
      ${EPIC_STATUS_HEARTBEAT_SEC:+--heartbeat-sec "$EPIC_STATUS_HEARTBEAT_SEC"} \
      ${EPIC_STREAM_IDLE_TIMEOUT_SEC:+--idle-timeout "$EPIC_STREAM_IDLE_TIMEOUT_SEC"} \
      --progress-mode "$progress_mode" \
      --log "$log_file" \
      ${SESSION_MODEL:+--expected-model "$SESSION_MODEL"} \
      "${stdin_file_args[@]}" \
      -- "${command[@]}")
    rc=$?
  fi
  return "$rc"
}

if [[ "${BASH_SOURCE[0]}" != "$0" ]]; then
  set -- "${_LOOP_SOURCE_ARGS[@]}"
  return 0
fi

_print_prepare_summary() {
  local prep_json="$1"
  if [[ "$VERBOSE" == "1" ]]; then
    echo "$prep_json"
  else
    echo "$prep_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
print("==> prepare:", "ok" if r.get("ok") else r.get("reason"))
phase = r.get("phase") or r.get("loop_phase") or ""
step = r.get("armed_step") or ""
if phase or step:
    print("==> working:", (phase or "?"), "step=" + (step or "?"))
if r.get("degraded"):
    print("==> WARN: context degraded — agent chooses next step from files")
    errs=r.get("shape_errors") or []
    if errs: print("==> shape:", "; ".join(errs)[:200])
if r.get("load_now"): print("==> load_now:", ", ".join(r["load_now"][:4]))
' 2>/dev/null || echo "$prep_json"
  fi
}

_apply_prepare_session_vars() {
  local prep_json="$1"
  EPIC_RUNTIME_RESOLVED="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("runtime") or "claude")' 2>/dev/null || echo claude)"
  EXTRAS_JSON="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.dumps(json.load(sys.stdin).get("runtime_extras") or {}))' 2>/dev/null || echo '{}')"
  export EPIC_RUNTIME_RESOLVED EXTRAS_JSON
  configure_runtime_env "$EPIC_RUNTIME_RESOLVED"
  SESSION_MODEL="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("model") or "")' 2>/dev/null || true)"
  LOOP_PHASE="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("loop_phase") or "")' 2>/dev/null || true)"
  MODEL_SOURCE="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("model_source") or "")' 2>/dev/null || true)"
  ARMED_STEP="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("armed_step") or "")' 2>/dev/null || true)"
  MODEL_ARGS=()
  if [[ -n "$SESSION_MODEL" ]]; then
    MODEL_ARGS=(--model "$SESSION_MODEL")
  elif [[ -n "${MODEL:-}" ]]; then
    MODEL_ARGS=(--model "$MODEL")
    SESSION_MODEL="$MODEL"
  fi
  fp_before="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("fingerprint") or "")')"
  prompt_file="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin)["prompt_file"])')"
}

_run_context_prepare() {
  set +e
  if [[ -n "${MODEL:-}" ]]; then
    PREP_JSON="$("${CTX[@]}" prepare --model "$MODEL")"
  else
    PREP_JSON="$("${CTX[@]}" prepare)"
  fi
  PREP_RC=$?
  set -e
}

_print_projection_banner() {
  local label="${1:-}"
  if [[ -n "$label" ]]; then
    echo "==> prompt (projection) [$label]:"
  else
    echo "==> prompt (projection):"
  fi
  awk '
    /^## projection$/ {show=1}
    show {print; if (/^- step:/) exit}
  ' "$prompt_file"
  if [[ -n "$ARMED_STEP" ]]; then
    echo "==> armed_step: $ARMED_STEP"
  fi
  echo "..."
}

# Transient API retry must re-prepare: memory-bank may advance during try 1 while
# armed_step/prompt_file were frozen at outer prepare (index.yaml SoT).
# Returns: 0=ok | 1=resume outer loop | 2=epic done (skip stale retry)
_reprepare_for_transient_retry() {
  local prev_step="${ARMED_STEP:-}"
  local next_try="$1"
  _run_context_prepare
  _print_prepare_summary "$PREP_JSON"
  if [[ $PREP_RC -eq 3 ]]; then
    local prep_stop
    prep_stop="$(echo "$PREP_JSON" | python3 -c 'import json,sys; r=json.load(sys.stdin); print(r.get("stop") or "")' 2>/dev/null || true)"
    if [[ "$prep_stop" == "EPIC_DONE" ]]; then
      echo "==> transient retry: epic complete — skip stale armed_step=${prev_step:-?} retry"
      return 2
    fi
    echo "==> WARN: transient retry prepare stopped (rc=3 stop=${prep_stop:-?}) — resume outer loop" >&2
    return 1
  fi
  if [[ $PREP_RC -ne 0 ]]; then
    local prep_halt prep_reason
    prep_halt="$(echo "$PREP_JSON" | python3 -c 'import json,sys; print("1" if json.load(sys.stdin).get("halt") else "0")' 2>/dev/null || echo 0)"
    prep_reason="$(echo "$PREP_JSON" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("reason") or "")' 2>/dev/null || true)"
    if [[ "$prep_halt" == "1" ]]; then
      echo "==> HALT: transient retry prepare fail-closed" >&2
      [[ -n "$prep_reason" ]] && echo "==> reason: $prep_reason" >&2
      exit "$PREP_RC"
    fi
    echo "==> WARN: transient retry prepare failed (rc=$PREP_RC) — resume outer loop" >&2
    [[ -n "$prep_reason" ]] && echo "==> reason: $prep_reason" >&2
    return 1
  fi
  _apply_prepare_session_vars "$PREP_JSON"
  echo "==> session model=${SESSION_MODEL:-default} phase=${LOOP_PHASE:-?} step=${ARMED_STEP:-?} source=${MODEL_SOURCE:-cli}"
  if [[ -n "$prev_step" && "$ARMED_STEP" != "$prev_step" ]]; then
    echo "==> transient retry: armed_step resynced ${prev_step} → ${ARMED_STEP:-?}"
  else
    echo "==> transient retry: re-prepared (step=${ARMED_STEP:-?})"
  fi
  _print_projection_banner "retry t${next_try}"
  return 0
}

echo "==> context-first loop cli_model=${MODEL:-default} epic=${EPIC_SPEC:-<activeContext>} claude=$CLAUDE"
echo "==> phase models: PROJECT_LOOP_<PHASE>_MODEL from .claude/project.env (DECOMPOSE/IMPLEMENT/…)"

# Fresh process start: drop leftover open incidents so a prior fail-closed
# (e.g. unrepaired finish_integrity_decompose_missing) does not halt check-after.
# Mid-run incidents still persist across sessions inside this process.
set +e
_clear_json="$("${CTX[@]}" incident-clear-open --json)"
_clear_rc=$?
set -e
if [[ $_clear_rc -eq 0 ]]; then
  echo "$_clear_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
n=int(r.get("cleared_count") or 0)
if n:
    codes=",".join(r.get("diagnostic_codes") or []) or "?"
    print(f"==> cleared {n} open incident(s) on loop start ({codes})")
' 2>/dev/null || true
fi
unset _clear_json _clear_rc

iter=0
while true; do
  iter=$((iter + 1))
  echo ""
  echo "======== SESSION $iter ========"

  # Bound session-*.log growth (newest EPIC_SESSION_LOG_KEEP kept; default 10).
  python3 - "$STATE_DIR" "${EPIC_SESSION_LOG_KEEP:-10}" <<'PY' || true
import sys
from pathlib import Path
d = Path(sys.argv[1])
keep = max(1, int(sys.argv[2]))
if not d.is_dir():
    raise SystemExit(0)
logs = sorted(d.glob("session-*.log"), key=lambda p: p.stat().st_mtime, reverse=True)
removed = 0
for path in logs[keep:]:
    try:
        path.unlink()
        removed += 1
    except OSError:
        pass
if removed:
    print(f"==> pruned {removed} old session log(s); kept {min(keep, len(logs))}")
PY

  _run_context_prepare
  prep_json="$PREP_JSON"
  prep_rc=$PREP_RC
  _print_prepare_summary "$prep_json"
  if [[ $prep_rc -eq 3 ]]; then
    prep_stop="$(echo "$prep_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print(r.get("stop") or "")' 2>/dev/null || true)"
    if [[ "$prep_stop" == "EPIC_DONE" && "${EPIC_CHAIN_ROADMAP:-0}" == "1" ]]; then
      set +e
      advance_json="$("${CTX[@]}" roadmap-advance)"
      advance_rc=$?
      set -e
      if [[ "$VERBOSE" == "1" ]]; then
        echo "$advance_json"
      else
        echo "$advance_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
print("==> roadmap-advance:", r.get("epic") or r.get("stop") or r.get("reason") or r.get("complete"))
' 2>/dev/null || echo "$advance_json"
      fi
      if [[ $advance_rc -eq 0 ]]; then
        continue
      fi
      if [[ $advance_rc -eq 3 ]]; then
        echo "==> LOOP COMPLETE (roadmap queue)"
        exit 0
      fi
      echo "==> ERROR: roadmap-advance failed after prepare EPIC_DONE (rc=$advance_rc)" >&2
      exit 1
    fi
    echo "==> LOOP COMPLETE (stop marker)"
    exit 0
  fi
  if [[ $prep_rc -ne 0 ]]; then
    prep_halt="$(echo "$prep_json" | python3 -c 'import json,sys; print("1" if json.load(sys.stdin).get("halt") else "0")' 2>/dev/null || echo 0)"
    prep_reason="$(echo "$prep_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("reason") or "")' 2>/dev/null || true)"
    prep_diags="$(echo "$prep_json" | python3 -c 'import json,sys; print(",".join(json.load(sys.stdin).get("diagnostic_codes") or []))' 2>/dev/null || true)"
    if [[ "$prep_halt" == "1" ]]; then
      echo "==> HALT: prepare fail-closed (diagnostic_codes=${prep_diags:-none})" >&2
      [[ -n "$prep_reason" ]] && echo "==> reason: $prep_reason" >&2
      exit "$prep_rc"
    fi
    echo "==> WARN: prepare failed (rc=$prep_rc) — retrying outer loop" >&2
    sleep 20
    continue
  fi

  _apply_prepare_session_vars "$prep_json"
  echo "==> session model=${SESSION_MODEL:-default} phase=${LOOP_PHASE:-?} step=${ARMED_STEP:-?} source=${MODEL_SOURCE:-cli}"

  _print_projection_banner

  transient_try=0
  max_transient="${EPIC_TRANSIENT_RETRY_MAX:-3}"
  resume_outer=0
  while true; do
    transient_try=$((transient_try + 1))
    session_tag="$iter"
    [[ $transient_try -gt 1 ]] && session_tag="${iter}-t${transient_try}"

    set +e
    run_agent_session "$session_tag" "$prompt_file"
    agent_rc=$?
    claude_rc="$agent_rc"
    if [[ $agent_rc -eq 130 || $agent_rc -eq 143 ]]; then
      _exit_loop_user_interrupt
    fi
    # Keep +e through diagnostics — echo to a broken tty must not kill retry.
    echo "==> claude exit=$claude_rc (try $transient_try/$max_transient)" || true
    session_log="$STATE_DIR/session-${session_tag}.log"

    rec_json="$("${CTX[@]}" record-session --log "$session_log" --exit-code "$claude_rc" --attempt "$transient_try" --runtime "$EPIC_RUNTIME_RESOLVED")"
    rec_rc=$?
    set -e

    if [[ $rec_rc -eq 0 ]]; then
      break
    fi

    retryable="$(echo "$rec_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print("1" if r.get("retryable") else "0")' 2>/dev/null || echo 0)"
    backoff="$(echo "$rec_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print(int(r.get("backoff_sec") or 0))' 2>/dev/null || echo 0)"
    reason="$(echo "$rec_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print(r.get("reason") or "")' 2>/dev/null || true)"

    if [[ "$retryable" == "1" && $transient_try -lt $max_transient ]]; then
      echo "==> TRANSIENT API abort — retry after ${backoff}s"
      echo "==> reason: $reason"
      [[ "$backoff" -gt 0 ]] && sleep "$backoff"
      set +e
      _reprepare_for_transient_retry "$((transient_try + 1))"
      reprep_rc=$?
      set -e
      if [[ $reprep_rc -eq 2 ]]; then
        rec_rc=0
        break
      fi
      if [[ $reprep_rc -ne 0 ]]; then
        resume_outer=1
        break
      fi
      continue
    fi

    if [[ "$retryable" == "1" ]]; then
      echo "==> TRANSIENT API abort — retry cap reached; resume in next outer session" >&2
      echo "==> reason: $reason" >&2
      resume_outer=1
      break
    fi

    outcome="$(echo "$rec_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("outcome") or "")' 2>/dev/null || true)"
    if [[ "$outcome" == "permanent_failure" ]] || [[ "$reason" == model_substitution* ]]; then
      echo "==> reason: $reason" >&2
      if [[ "$reason" == model_substitution* ]]; then
        echo "==> HALT: model/config fail-closed (no silent downgrade)" >&2
        echo "==> fix: allow requested model in org/OmniRoute, or unset PROJECT_LOOP_<PHASE>_MODEL / pass a reachable CLI MODEL" >&2
      elif [[ "$reason" == "command not found" ]]; then
        echo "==> HALT: runtime binary missing (fail-closed)" >&2
        echo "==> fix: install runtime CLI or set CODEX_BIN / CLAUDE_PATH / DSH_PATH" >&2
      else
        echo "==> HALT: permanent session failure (fail-closed)" >&2
      fi
      exit 1
    fi

    echo "==> SESSION ABORTED (non-retryable) — resuming outer loop" >&2
    echo "$rec_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); print("==> abort:", r.get("reason"), "kind=", r.get("abort_kind"))' 2>/dev/null || echo "$rec_json"
    resume_outer=1
    break
  done

  if [[ "$resume_outer" -eq 1 ]]; then
    continue
  fi

  set +e
  after_json="$("${CTX[@]}" check-after --fingerprint-before "$fp_before")"
  after_rc=$?
  set -e
  if [[ "$VERBOSE" == "1" ]]; then
    echo "$after_json"
  else
    echo "$after_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
print("==> after:", r.get("reason") or r.get("stop") or ("continue" if r.get("ok") else "halt"))
fr=r.get("fingerprint_repair") or {}
if fr.get("repaired"):
    print("==> fingerprint-repair:", fr.get("mode"), "step="+str(fr.get("step_id") or ""))
if r.get("retry_fingerprint_stall"):
    print("==> fingerprint-stall: outer retry", r.get("fingerprint_stall_count"), "(new agent)")
' 2>/dev/null || echo "$after_json"
  fi

  after_action="$(echo "$after_json" | python3 -c '
import json, sys
sys.path.insert(0, r"'"$HUB_ROOT"'/loop")
sys.path.insert(0, r"'"$HUB_ROOT"'/harness/hooks")
from halt_logic import decide_after_action
from epic_paths import epic_dir
from loop.incidents.trace import append_trace
res = json.load(sys.stdin)
action = decide_after_action(res)
ep_id = res.get("episode_id", "") if isinstance(res, dict) else ""
append_trace(epic_dir(r"'"$PROJECT_ROOT"'"), phase="decide", action="decide_after_action", decide=action, episode_id=ep_id, detail=res if isinstance(res, dict) else {})
print(action)
' 2>/dev/null || echo halt)"
  if [[ "$after_action" == "continue" ]]; then
    if echo "$after_json" | python3 -c 'import json,sys; r=json.load(sys.stdin); raise SystemExit(0 if r.get("retry_fingerprint_stall") else 1)' 2>/dev/null; then
      echo "==> WARN: fingerprint stall — spawning next session (autonomy retry)" >&2
      sleep 2
      continue
    fi
    continue
  fi
  if [[ "$after_action" == "halt" ]]; then
    if [[ "${EPIC_INCIDENT_TIER1:-1}" != "0" ]]; then
      set +e
      t1_check_json="$(python3 -c '
import sys
sys.path.insert(0, "'"$HUB_ROOT"'")
from pathlib import Path
from loop.incidents.store import list_open_incidents
from loop.incidents.tier1_runner import should_attempt_tier1, run_tier1_session
from loop.incidents.store import resolve_incident
from loop.epic_paths import epic_dir

e_dir = epic_dir("'"$PROJECT_ROOT"'")
p_root = Path("'"$PROJECT_ROOT"'")
open_incs = list_open_incidents(e_dir)
if open_incs:
    inc = open_incs[0]
    if should_attempt_tier1(inc, e_dir):
        res = run_tier1_session(inc, e_dir, p_root)
        if res.success:
            resolve_incident(e_dir, inc.incident_id, resolution={"resolution_tier": "tier1", "resolution_action": "tier1_autofix"})
            print("TIER1_SUCCESS")
        else:
            print("TIER1_FAIL")
    else:
        print("NOT_ELIGIBLE")
else:
    print("NO_OPEN_INCIDENTS")
' 2>/dev/null || echo "TIER1_ERROR")"
      set -e

      if [[ "$t1_check_json" == "TIER1_SUCCESS" ]]; then
        echo "==> tier1 session succeeded; retrying outer loop"
        continue
      fi
    fi

    after_stop="$(echo "$after_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("stop") or "")' 2>/dev/null || true)"
    after_reason="$(echo "$after_json" | python3 -c 'import json,sys; print(json.load(sys.stdin).get("reason") or "")' 2>/dev/null || true)"
    if [[ "$after_stop" == NEED_HUMAN* ]]; then
      echo "==> HALT: NEED_HUMAN — $after_stop" >&2
    elif [[ -n "$after_stop" ]]; then
      echo "==> HALT: $after_stop" >&2
    elif [[ -n "$after_reason" ]]; then
      echo "==> HALT: $after_reason" >&2
    else
      echo "==> HALT: check-after fail-closed (rc=$after_rc)" >&2
    fi
    exit 1
  fi
  if [[ "$after_action" == "complete" ]]; then
    chk_sb="$(python3 -c 'import json,pathlib; p=pathlib.Path("runtime/dev-hub/epic/checkpoint.json"); print(json.loads(p.read_text()).get("session_boundary") if p.is_file() else "")' 2>/dev/null || true)"
    if [[ "$chk_sb" == "True" || "$chk_sb" == "true" ]]; then
      echo "==> SESSION_BOUNDARY: step finalized with session_boundary gate"
    fi
    if [[ "${EPIC_CHAIN_ROADMAP:-0}" == "1" ]]; then
      set +e
      advance_json="$("${CTX[@]}" roadmap-advance)"
      advance_rc=$?
      set -e
      if [[ "$VERBOSE" == "1" ]]; then
        echo "$advance_json"
      else
        echo "$advance_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
print("==> roadmap-advance:", r.get("epic") or r.get("stop") or r.get("reason") or r.get("complete"))
' 2>/dev/null || echo "$advance_json"
      fi
      if [[ $advance_rc -eq 0 ]]; then
        continue
      fi
      if [[ $advance_rc -eq 3 ]]; then
        echo "==> LOOP COMPLETE (roadmap queue)"
        exit 0
      fi
      echo "==> ERROR: roadmap-advance failed (rc=$advance_rc)" >&2
      exit 1
    fi
    set +e
    fanout_json="$("${CTX[@]}" dag-fanout)"
    fanout_rc=$?
    set -e
    if [[ "$VERBOSE" == "1" ]]; then
      echo "$fanout_json"
    else
      echo "$fanout_json" | python3 -c '
import json,sys
r=json.load(sys.stdin)
print("==> fanout:", r.get("node") or r.get("reason") or r.get("complete"))
' 2>/dev/null || echo "$fanout_json"
    fi
    if [[ $fanout_rc -eq 0 ]]; then
      continue
    fi
    if [[ $fanout_rc -ne 3 ]]; then
      echo "==> WARN: DAG fanout failed (rc=$fanout_rc) — retrying outer loop" >&2
      sleep 20
      continue
    fi
    echo "==> LOOP COMPLETE (DAG journey)"
    exit 0
  fi
done
