from __future__ import annotations

import re

import yaml

GENERATED_HEADER = "# GENERATED by runtime-sync from harness/manifest.yaml — DO NOT EDIT"

_FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n?", re.DOTALL)


class CodexAgentTomlError(ValueError):
    pass


def split_markdown_frontmatter(text: str) -> tuple[dict[str, object], str]:
    match = _FRONTMATTER_RE.match(text)
    if not match:
        return {}, text.strip()
    meta = yaml.safe_load(match.group(1)) or {}
    if not isinstance(meta, dict):
        raise CodexAgentTomlError("agent frontmatter must be a mapping")
    body = text[match.end() :].strip()
    return meta, body


def _toml_basic_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_literal_multiline(value: str) -> str:
    if "'''" in value:
        escaped = value.replace("\\", "\\\\").replace('"""', '\\"""')
        return f'"""\n{escaped}\n"""'
    return f"'''\n{value}\n'''"


def render_codex_agent_toml(
    *,
    name: str,
    description: str,
    developer_instructions: str,
) -> str:
    agent_name = name.strip()
    agent_description = description.strip()
    instructions = developer_instructions.strip()
    if not agent_name:
        raise CodexAgentTomlError("agent name is required")
    if not agent_description:
        raise CodexAgentTomlError("agent description is required")
    if not instructions:
        raise CodexAgentTomlError("developer_instructions body is required")

    lines = [
        GENERATED_HEADER,
        "",
        f"name = {_toml_basic_string(agent_name)}",
        f"description = {_toml_basic_string(agent_description)}",
        f"developer_instructions = {_toml_literal_multiline(instructions)}",
    ]
    return "\n".join(lines) + "\n"


def markdown_agent_to_codex_toml(
    src_text: str,
    *,
    fallback_name: str,
    fallback_description: str = "",
) -> str:
    meta, body = split_markdown_frontmatter(src_text)
    name = str(meta.get("name") or fallback_name).strip()
    description = str(meta.get("description") or fallback_description or "").strip()
    instructions = body or src_text.strip()
    return render_codex_agent_toml(
        name=name,
        description=description,
        developer_instructions=instructions,
    )
