from __future__ import annotations

import hashlib
import json
from pathlib import Path
from loop.runtime_materializers.manifest_schema import HarnessManifest

GENERATED_HEADER = "// GENERATED by runtime-sync from harness/manifest.yaml — DO NOT EDIT"
HOOKS_META_NAME = "hooks.meta.json"

EVENT_MAPPING: dict[str, str] = {
    "stop-gate": "Stop",
    "spawn-validate": "UserPromptSubmit",
    "session-start": "SessionStart",
}


def hooks_meta_path(dest: Path) -> Path:
    return dest.parent / HOOKS_META_NAME


def generate_hooks_json(
    manifest: HarnessManifest,
    manifest_path: str | Path,
    dest: str | Path,
    repo_root: str | Path | None = None,
) -> None:
    manifest_path = Path(manifest_path)
    dest = Path(dest)

    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest file not found: {manifest_path}")

    manifest_bytes = manifest_path.read_bytes()
    manifest_hash = hashlib.sha256(manifest_bytes).hexdigest()

    if repo_root is None:
        repo_root = dest.parent.parent

    repo_root = Path(repo_root)

    hooks_dict: dict[str, list[dict[str, str]]] = {}

    for hook_name, hook_def in manifest.hooks.items():
        codex_config = hook_def.runtimes.get("codex", {})
        if not codex_config.get("hooks_json_entry"):
            continue

        source_path = repo_root / hook_def.source
        if not source_path.exists():
            raise FileNotFoundError(f"Hook source file does not exist: {source_path}")

        event_name = EVENT_MAPPING.get(hook_name, hook_name)

        command = f"python3 {hook_def.source}"
        hooks_dict[event_name] = [
            {
                "type": "command",
                "command": command,
            }
        ]

    data = {"hooks": hooks_dict}
    meta = {
        "header": GENERATED_HEADER,
        "manifest_hash": manifest_hash,
    }

    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
    hooks_meta_path(dest).write_text(json.dumps(meta, indent=2) + "\n", encoding="utf-8")
