from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import Any

import yaml


HOOK_EVENTS = {
    "SessionStart": "session-start.py",
    "UserPromptSubmit": "user-prompt.py",
    "PreToolUse": "pretool-dispatch.py",
    "PostToolUse": "posttool-dispatch.py",
    "SubagentStart": "subagent-start.py",
    "SubagentStop": "subagent-stop.py",
    "Stop": "stop-gate.py",
}


def _hooks_payload() -> dict[str, Any]:
    hooks: dict[str, list[dict[str, Any]]] = {}
    for event, script in HOOK_EVENTS.items():
        item: dict[str, Any] = {
            "type": "command",
            "command": f"python3 harness/hooks/{script}",
        }
        if event in {"PreToolUse", "PostToolUse"}:
            item["matcher"] = ".*"
        if event == "PostToolUse":
            item["timeout_ms"] = 45000
        hooks[event] = [item]
    return {"hooks": hooks}


def _manifest(path: Path) -> dict[str, Any]:
    payload = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
    if not isinstance(payload, dict):
        raise ValueError(f"invalid manifest: {path}")
    return payload


_FRONTMATTER_RE = re.compile(r"^---\r?\n(.*?)\r?\n---\r?\n?", re.DOTALL)
_NATIVE_SETTING_RE = re.compile(r"^(model|model_reasoning_effort|sandbox_mode)\s*=\s*\"([^\"]*)\"\s*$", re.MULTILINE)


def _agent_source(root: Path, definition: dict[str, Any]) -> tuple[Path, str, dict[str, Any], str]:
    source = root / str(definition.get("source") or "")
    if not source.is_file():
        raise ValueError(f"missing agent source file: {source}")
    text = source.read_text(encoding="utf-8")
    match = _FRONTMATTER_RE.match(text)
    if match:
        metadata = yaml.safe_load(match.group(1)) or {}
        body = text[match.end() :].strip()
    else:
        metadata = {}
        body = text.strip()
    if not isinstance(metadata, dict):
        raise ValueError(f"invalid agent frontmatter: {source}")
    return source, body, metadata, hashlib.sha256(text.encode("utf-8")).hexdigest()


def _native_settings(target: Path) -> dict[str, str]:
    if not target.is_file():
        return {}
    return {key: value for key, value in _NATIVE_SETTING_RE.findall(target.read_text(encoding="utf-8"))}


def _toml_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _toml_instructions(value: str) -> str:
    if "'''" not in value:
        return "'''\n" + value + "\n'''"
    return '"""\n' + value.replace('"""', '\\"""') + '\n"""'


def _render_agent(root: Path, agent_id: str, definition: dict[str, Any], target: Path) -> tuple[str, str]:
    source, body, metadata, source_hash = _agent_source(root, definition)
    name = str(metadata.get("name") or agent_id).strip()
    description = str(metadata.get("description") or definition.get("description") or "").strip()
    settings = _native_settings(target)
    lines = [
        "# GENERATED by runtime-sync from harness/manifest.yaml — DO NOT EDIT",
        f"# source_prompt_sha256: {source_hash}",
        "",
        f"name = {_toml_string(name)}",
        f"description = {_toml_string(description)}",
    ]
    for key in ("model", "model_reasoning_effort", "sandbox_mode"):
        if key in settings:
            lines.append(f"{key} = {_toml_string(settings[key])}")
    lines.append(f"developer_instructions = {_toml_instructions(body)}")
    return "\n".join(lines) + "\n", source_hash


def _materialize_agents(root: Path, manifest: dict[str, Any]) -> list[Path]:
    targets: list[Path] = []
    for agent_id, definition in (manifest.get("agents") or {}).items():
        if not isinstance(definition, dict):
            continue
        runtime = ((definition.get("runtimes") or {}).get("codex") or {})
        if not runtime.get("materialize"):
            continue
        target = root / str(runtime.get("target") or f".codex/agents/{agent_id}.toml")
        target.parent.mkdir(parents=True, exist_ok=True)
        content, source_hash = _render_agent(root, agent_id, definition, target)
        target.write_text(content, encoding="utf-8")
        sidecar = target.with_name(f"{target.stem}.policy.json")
        if sidecar.is_file():
            try:
                policy = json.loads(sidecar.read_text(encoding="utf-8"))
            except (OSError, json.JSONDecodeError):
                policy = {}
            if isinstance(policy, dict):
                policy["source_prompt_sha256"] = source_hash
                sidecar.write_text(json.dumps(policy, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
        targets.append(target)
    return targets


def _drift(root: Path, manifest_path: Path, hooks_path: Path) -> list[str]:
    issues: list[str] = []
    if not hooks_path.is_file():
        issues.append(f"missing hooks file: {hooks_path}")
    else:
        try:
            actual = json.loads(hooks_path.read_text(encoding="utf-8"))
        except json.JSONDecodeError:
            issues.append(f"invalid hooks JSON: {hooks_path}")
        else:
            if actual != _hooks_payload():
                issues.append(f"hooks drift: {hooks_path}")

    manifest = _manifest(manifest_path)
    for agent_id, definition in (manifest.get("agents") or {}).items():
        if not isinstance(definition, dict):
            issues.append(f"invalid agent definition: {agent_id}")
            continue
        runtime = ((definition.get("runtimes") or {}).get("codex") or {})
        if runtime.get("materialize"):
            target = root / str(runtime.get("target") or "")
            if not target.is_file():
                issues.append(f"missing codex agent: {target}")
                continue
            try:
                _, _, _, source_hash = _agent_source(root, definition)
            except ValueError as exc:
                issues.append(str(exc))
                continue
            marker = f"# source_prompt_sha256: {source_hash}"
            if marker not in target.read_text(encoding="utf-8"):
                issues.append(f"codex agent drift: {target}")
    for script in HOOK_EVENTS.values():
        path = root / "harness" / "hooks" / script
        if not path.is_file():
            issues.append(f"missing hook entrypoint: {path}")
    return issues


def _apply(root: Path, hooks_path: Path, manifest_path: Path) -> None:
    manifest = _manifest(manifest_path)
    _materialize_agents(root, manifest)
    hooks_path.parent.mkdir(parents=True, exist_ok=True)
    hooks_path.write_text(
        json.dumps(_hooks_payload(), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Validate loop runtime materialization")
    parser.add_argument("--manifest", type=Path)
    parser.add_argument("--hooks-json", type=Path)
    parser.add_argument("--root-dir", type=Path)
    parser.add_argument("--runtime", choices=("codex", "claude", "all"), default="codex")
    parser.add_argument("--allow-hash-mismatch", action="store_true")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true")
    group.add_argument("--apply", action="store_true")
    args = parser.parse_args(argv)

    root = (args.root_dir or Path(__file__).resolve().parents[2]).resolve()
    manifest_path = (args.manifest or root / "harness" / "manifest.yaml").resolve()
    hooks_path = (args.hooks_json or root / ".codex" / "hooks.json").resolve()
    if not manifest_path.is_file():
        print(f"Manifest file not found: {manifest_path}", file=sys.stderr)
        return 1
    if args.runtime == "claude":
        return 0
    issues = _drift(root, manifest_path, hooks_path)
    if args.apply:
        _apply(root, hooks_path, manifest_path)
        issues = _drift(root, manifest_path, hooks_path)
    if issues:
        for issue in issues:
            print(issue, file=sys.stderr)
        return 1
    print("No drift detected" if args.check else "Applied runtime 'codex'")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
